//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.inv_movencabezado = new HashSet<inv_movencabezado>();
        }
    
        public int CodCliente { get; set; }
        public string NombreCliente { get; set; }
        public string RNC { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string TelMovil { get; set; }
        public string Email { get; set; }
        public string Contacto { get; set; }
        public bool EstadoCli { get; set; }
        public int TipoPrecio { get; set; }
    
        public virtual ICollection<inv_movencabezado> inv_movencabezado { get; set; }
    }
}
