//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public documento()
        {
            this.inv_movencabezado = new HashSet<inv_movencabezado>();
        }
    
        public string tipoDocumento { get; set; }
        public string Descripcion { get; set; }
        public int ultimonumero { get; set; }
        public Nullable<decimal> EfectoExistencia { get; set; }
    
        public virtual ICollection<inv_movencabezado> inv_movencabezado { get; set; }
    }
}
