//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_movdetalle
    {
        public int idMovimiento { get; set; }
        public int fila { get; set; }
        public int Codigo { get; set; }
        public decimal Precio { get; set; }
        public decimal costo { get; set; }
        public int Cantidad { get; set; }
        public decimal impuesto { get; set; }
    
        public virtual inv_movencabezado inv_movencabezado { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
