//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_movencabezado
    {
        public inv_movencabezado()
        {
            this.inv_movdetalle = new HashSet<inv_movdetalle>();
        }
    
        public int idMovimiento { get; set; }
        public string tipoDocumento { get; set; }
        public int numeroDoc { get; set; }
        public int CodTercero { get; set; }
        public int CodUsuario { get; set; }
        public string rnc { get; set; }
        public string idNCF { get; set; }
        public string ncf { get; set; }
        public string ncfAfectado { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal totalExento { get; set; }
        public string totalGravado { get; set; }
        public decimal Impuesto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public decimal Total { get; set; }
        public bool Estado { get; set; }
        public Nullable<decimal> EfectoExistencia { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual comprobanteTipo comprobanteTipo { get; set; }
        public virtual documento documento { get; set; }
        public virtual ICollection<inv_movdetalle> inv_movdetalle { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
