//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFact
    {
        public string CodigoProd { get; set; }
        public int CodigoFact { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
