//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.DetalleFact = new HashSet<DetalleFact>();
        }
    
        public int CodigoFact { get; set; }
        public int CodCliente { get; set; }
        public int CodUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Impuesto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public decimal Total { get; set; }
        public bool Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<DetalleFact> DetalleFact { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
